listen              1935;
max_connections     1000;

daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
    crossdomain     on;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain     on;
}

vhost __defaultVhost__ {

    hls {
        enabled         on;

        hls_path        ./objs/nginx/html;

        # HLS 조각 길이
        hls_fragment    2;

        # 재생목록에 유지할 총 시간
        hls_window      10;
    }
}